{% set name = "citric" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/citric-{{ version }}.tar.gz
  sha256: 741fd09b097bb8c205bf545d203d890c8157476a207e5fc10eaf6a0de843ba99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.25.1

test:
  imports:
    - citric
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edgarrmondragon/citric
  summary: A client to the LimeSurvey Remote Control API 2, written in modern Python.
  description: |
    ## Features

    - Supports the full RPC API via the [`Session` class](https://citric.readthedocs.io/en/latest/_api/citric/session/index.html#citric.session.Session).  
    - Best effort to implement all the RPC methods in the [`Client` class](https://citric.readthedocs.io/en/stable/_api/citric/index.html#citric.Client). See the [API coverage page](https://citric.readthedocs.io/en/stable/rpc_coverage.html) for details.
    - Easily export survey data to CSV files, [Pandas DataFrames](https://citric.readthedocs.io/en/stable/how-to.html#export-responses-to-a-pandas-dataframe) and [DuckDB databases](https://citric.readthedocs.io/en/stable/how-to.html#export-responses-to-a-duckdb-database-and-analyze-with-sql).
    - Easily [download survey files](https://citric.readthedocs.io/en/stable/how-to.html#get-files-uploaded-to-a-survey-and-move-them-to-s3) (e.g. images, audio, etc.) to a local directory.
    - Tested against LimeSurvey 6.0.0+ and 5.0.0+ versions.
    - Experimental support for the new [REST API](https://manual.limesurvey.org/REST_API).

    ## Usage

    ```python
    from citric import Client

    # Connect to your LimeSurvey instance
    client =  Client(
        "https://mylimesite.limequery.com/admin/remotecontrol",
        "myusername",
        "mypassword",
    )

    # Print the LimeSurvey version
    print(client.get_server_version())

    # Print every survey's title
    for survey in client.list_surveys():
        print(survey["surveyls_title"])
    ```

  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - edgarrmondragon
