{% set name = "citric" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/citric-{{ version }}.tar.gz
  sha256: ffdd922884bdac3740765010b4ba6bc63a5a7cfb5d55591b4a72a284461df9ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
    - trove-classifiers >=2025.5.7.19  # Programming Language :: Python :: 3.15
  run:
    - python >={{ python_min }}
    - backports-strenum >=1.3.1  # technically python_version<"3.11"
    - requests >=2.25.1
    - typing-extensions >=4.6  # technically python_version<"3.12"


test:
  imports:
    - citric
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edgarrmondragon/citric
  summary: A client to the LimeSurvey Remote Control API 2, written in modern Python.
  description: |
    - Supports the full RPC API via the `Session` class.
    - Best effort to implement all the RPC methods in the `Client` class.
    - Easily export survey data to CSV files, Pandas DataFrames and DuckDB databases.
    - Easily download survey files (e.g. images, audio, etc.) to a local directory.
    - Tested against LimeSurvey 6.0.0+ and 5.0.0+ versions.
    - Experimental support for the new [REST API](https://manual.limesurvey.org/REST_API).
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/edgarrmondragon/citric
  doc_url: https://citric.readthedocs.io/
  doc_source_url: https://github.com/edgarrmondragon/citric/tree/main/docs

extra:
  recipe-maintainers:
    - edgarrmondragon
