{% set name = "citric" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/citric-{{ version }}.tar.gz
  sha256: 741fd09b097bb8c205bf545d203d890c8157476a207e5fc10eaf6a0de843ba99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.25.1

test:
  imports:
    - citric
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edgarrmondragon/citric
  summary: A client to the LimeSurvey Remote Control API 2, written in modern Python.
  description: |
    <h2>Usage</h2>

    ```python
    from citric import Client

    client =  Client(
        "https://mylimesite.limequery.com/admin/remotecontrol",
        "myusername",
        "mypassword",
    )

    for survey in client.list_surveys():
        print(survey["surveyls_title"])
    ```

  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/edgarrmondragon/citric
  doc_url: https://citric.readthedocs.io/
  doc_source_url: https://github.com/edgarrmondragon/citric/tree/main/docs

extra:
  recipe-maintainers:
    - edgarrmondragon
