{% set name = "citric" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/citric-{{ version }}.tar.gz
  sha256: 34f3353768770ad7de8202f5efcca3eb1297af9915d9842f7d03d8e8497d58a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.25.1

test:
  imports:
    - citric
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edgarrmondragon/citric
  summary: A client to the LimeSurvey Remote Control API 2, written in modern Python.
  description: |
    - Supports the full RPC API via the `Session` class.
    - Best effort to implement all the RPC methods in the `Client` class.
    - Easily export survey data to CSV files, Pandas DataFrames and DuckDB databases.
    - Easily download survey files (e.g. images, audio, etc.) to a local directory.
    - Tested against LimeSurvey 6.0.0+ and 5.0.0+ versions.
    - Experimental support for the new [REST API](https://manual.limesurvey.org/REST_API).
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/edgarrmondragon/citric
  doc_url: https://citric.readthedocs.io/
  doc_source_url: https://github.com/edgarrmondragon/citric/tree/main/docs

extra:
  recipe-maintainers:
    - edgarrmondragon
